openssl_keys:
    root:
        client: client.0
        key-type: rsa:4096
        cn: teuthology
        install: [client.0]
    rgw.client.0:
        client: client.0
        ca: root
        embed-key: true
rgw:
    client.0:
        ssl certificate: rgw.client.0
tasks:
- s3tests-java:
    client.0:
        branch: wip
        repo: 'https://github.com/adamyanova/java_s3tests.git'
